[project]
name="ApolloTLR-replicate"
version="0.0.1"

[build-system]
requires = ["setuptools", "importlib_resources"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"tlr.confs" = ["*.json"]
"tlr.weights" = ["*.torch"]